version: "3.7"

services:
  db:
    container_name: chat-db
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      PGDATA: /data/postgres
    healthcheck:
      test: pg_isready -U user
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
    postgres:
